#!/bin/bash
#############################################################
# Author: Matthew Zygowicz
# Filename: compress_archive
# Usage: compress_archive
# Example: compress_archive
#############################################################

DEBUG=1

# Runs the following as a root cronjob every 5 minutes
#sudo mount -t cifs //<NETWORK_COMPUTED>/<PATH> /mnt/gemini/garage -o uid=<UNIXUSER>,gid=<UNIXGROUP>username=<USERNAME>,password=<PASSWORD>

#[ "$OSTYPE" = linux-gnu ] && date --date="2 days ago" +"%Y"-"%m"/"%d" || date -v-2d +"%Y"-"%m"/"%d"

MOUNTED_DRIVE='/mnt/gemini/garage'
ARCHIVE_DIR='/mnt/gemini/garage/Archive'
ARCHIVE_FILE_NAME=$([ "$OSTYPE" = linux-gnu ] && date --date="2 days ago" +"%Y"-"%m"-"%d" || date -v-2d +"%Y"-"%m"-"%d")
DATE_DIR=$([ "$OSTYPE" = linux-gnu ] && date --date="2 days ago" +"%Y"-"%m"/"%d" || date -v-2d +"%Y"-"%m"/"%d")

echo "Running command: tar cf - ${MOUNTED_DRIVE}/${DATE_DIR} | 7z a -si ${ARCHIVE_DIR}/${ARCHIVE_FILE_NAME}.tar.7z"
tar cf - ${MOUNTED_DRIVE}/${DATE_DIR} | 7z a -si ${ARCHIVE_DIR}/${ARCHIVE_FILE_NAME}.tar.7z

if [ -n "$MOUNTED_DRIVE" ] && [ -n "$DATE_DIR" ] ; then
  rm -r ${MOUNTED_DRIVE}/${DATE_DIR}
fi
